# Daily Coding challenge #112 (2025-11-30) - freeCodeCamp.org
# AI Detector
# Today's challenge is inspired by the release of ChatGPT on November 30, 2022.

# Given a string of one or more sentences, determine if it was likely generated by AI
# using the following rules:

# It contains two or more dashes (-).

# It contains two or more sets of parenthesis (()). Text can be within the parenthesis.

# It contains three or more words with 7 or more letters.

# Words are separated by a single space and only consist of letters (A-Z). Don't
# include punctuation or other non-letters as part of a word.

# If the given sentence meets any of the rules above, return "AI", otherwise,
# return "Human".
from pytest import mark


def detect_ai(text: str) -> str:
    # Split by spaces and remove non-letters from each word
    words = [''.join(c for c in word if c.isalpha()) for word in text.split()]

    has_multiple_dashes = text.count('-') >= 2
    has_multiple_parentheses = text.count('(') >= 2
    has_long_words = sum(1 for word in words if len(word) >= 7) >= 3

    return (
        'AI'
        if (has_multiple_dashes or has_multiple_parentheses or has_long_words)
        else 'Human'
    )


tests = [
    ('The quick brown fox jumped over the lazy dog.', 'Human'),
    ('The hypersonic brown fox - jumped (over) the lazy dog.', 'Human'),
    ("Yes - you're right! I made a mistake there - let me try again.", 'AI'),
    ('The extraordinary students were studying vivaciously.', 'AI'),
    ('The (excited) student was (coding) in the library.', 'AI'),
]


@mark.parametrize('text,expected', tests)
def test_detect_ai(text: str, expected: str) -> None:
    assert detect_ai(text) == expected


if __name__ == '__main__':
    text, expected = tests[0]
    print(detect_ai(text))
